---
  - name: Create a tracking directory if it does not exist
    file:
      path: '{{ tracking_dir_server }}/common_vs_local'
      state: directory
      mode: '0775'
      owner: '{{ user_for_eocecm }}'
      group: '{{ group_for_eocecm }}'
    become: yes

  - name: Save a SQL for Finland common vs local EOC count of SOF items
    template:
      src: fi_common_local_eoc_sof_items.j2
      dest: '{{ tracking_dir_server }}/common_vs_local/fi_common_local_eoc_sof_items_{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}_{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}.sql'
      mode: '0775'
      owner: '{{ user_for_eocecm }}'
      group: '{{ group_for_eocecm }}'
    become: yes

  - name: Run a SQL for Finland common vs local EOC count of SOF items
    shell: './run_EDB_DDL_via_cmd_line_linux.sh {{ eoc_db_host }} 5444 {{ eoc_db_user }} {{ eoc_db_pass }} {{ eoc_db_database }} {{ tracking_dir_server }}/common_vs_local/fi_common_local_eoc_sof_items_{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}_{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}.sql {{ tracking_dir_server }}/common_vs_local/fi_common_local_eoc_sof_items_{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}_{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}.log'
    args:
      chdir: '{{ symlink_eoc_dir }}/DDL/edb'
    vars:
      java_home_var: '{{ folder_dest }}/java/current_jdk'
    environment:
      PATH: '{{ java_home_var }}/bin:/usr/edb/as11/bin:{{ ansible_env.PATH }}'
      EDBHOME: /usr/edb/as11
      PGDATA: /usr/edb/as11/data
      PGLOCALEDIR: /usr/edb/as11/share/locale
    become: yes
    become_user: '{{ user_for_eocecm }}'
    register: 'common_local_eoc_sof_items'

  - name: Save email body for Finland
    template:
      src: fi_email_common_local_eoc_sof_items.j2
      dest: '{{ tracking_dir_server }}/common_vs_local/fi_email_common_local_eoc_sof_items_{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}_{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}.txt'
      mode: '0775'
      owner: '{{ user_for_eocecm }}'
      group: '{{ group_for_eocecm }}'
    become: yes

  - name: Store email txt from remote to DDS
    fetch:
      src: '{{ tracking_dir_server }}/common_vs_local/fi_email_common_local_eoc_sof_items_{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}_{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}.txt'
      dest: '/tmp/common_vs_local_email'
    register: 'fetch_email'

  - debug:
      var: fetch_email

  - name: Send email with results for common vs local catalog items
    shell: 'cat {{ fetch_email.dest }} | mailx -S smtp={{ smtp_server }} -r {{ email_from }} -s "Common vs Local EOC SOF Items - Finland" -v {{ email_to }}'
    delegate_to: localhost
