---
###############################################################################
#----------Ericsson Catalog Manager - Config Export -------------#
###############################################################################

  - name: Config Export using configExport.sh command
    shell: './configExport.sh {{ ecm_database_string }} {{ ecm_app_name }} {{ ecm_app_version }} {{ ecm_export_password }} {{ ecm_config_export_file }} {{ ecm_metadata_path }}'
    args:
      chdir: '{{ symlink_ecm_dir }}/designer/env'
    become: yes
    become_user: '{{ user_for_eocecm }}'
    register: 'configExport_sh'
    # ignore_errors: True

  - name: Save log from command
    copy:
      content: "{{ configExport_sh.stdout }}"
      dest: "{{ log_dir_eocecm }}/{{ ecm_file_name }}-configExport_sh_{{ date_and_time }}.log"
      mode: '0775'
      owner: '{{ user_for_eocecm }}'
      group: '{{ group_for_eocecm }}'
    become: yes
    become_user: '{{ user_for_eocecm }}'
    # when: deploy_to_env == 'DEV1'

  - name: Add command we used in previous task to log
    blockinfile:
      path: "{{ log_dir_eocecm }}/{{ ecm_file_name }}-configExport_sh_{{ date_and_time }}.log"
      block: |
        ##################################################################################################################################################
        ####### {{ configExport_sh.cmd }} #######
        ##################################################################################################################################################
      marker: "\n# {mark} ANSIBLE MANAGED BLOCK\n"
      insertbefore: BOF
    become: yes
    become_user: '{{ user_for_eocecm }}'

  - fail:
      msg: 'Following command FAILED: {{ configExport_sh.cmd }}.'
    when: configExport_sh.rc != 0
