---
  - name: Create a tracking directory if it does not exist
    file:
      path: '{{ tracking_dir_server }}/reusability_metrics'
      state: directory  
      mode: '0775'
      owner: '{{ user_for_eocecm }}'
      group: '{{ group_for_eocecm }}'
    become: yes

  - name: Save a SQL for Lithuania Reusability Metrics
    template:
      src: lt_reusability_metrics.j2
      dest: '{{ tracking_dir_server }}/reusability_metrics/lt_reusability_metrics_{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}_{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}.sql'
      mode: '0775'
      owner: '{{ user_for_eocecm }}'
      group: '{{ group_for_eocecm }}'
    become: yes

  - name: Run a SQL for Lithuania Reusability Metrics
    shell: './run_EDB_DDL_via_cmd_line_linux.sh {{ ecm_db_host }} 5444 {{ ecm_db_user }} {{ ecm_db_pass }} {{ ecm_db_database }} {{ tracking_dir_server }}/reusability_metrics/lt_reusability_metrics_{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}_{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}.sql {{ tracking_dir_server }}/reusability_metrics/lt_reusability_metrics_{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}_{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}.log'
    args:
      chdir: '{{ symlink_ecm_dir }}/DDL/edb'
    vars:
      java_home_var: '{{ folder_dest }}/java/current_jdk'
    environment:
      PATH: '{{ java_home_var }}/bin:/usr/edb/as11/bin:{{ ansible_env.PATH }}'
      EDBHOME: /usr/edb/as11
      PGDATA: /usr/edb/as11/data
      PGLOCALEDIR: /usr/edb/as11/share/locale
    become: yes
    become_user: '{{ user_for_eocecm }}'
    register: 'reusability_metrics'


  - name: Save email body for Lithuania
    template:
      src: lt_email_reusability_metrics.j2
      dest: '{{ tracking_dir_server }}/reusability_metrics/lt_reusability_metrics_{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}_{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}.txt'
      mode: '0775'
      owner: '{{ user_for_eocecm }}'
      group: '{{ group_for_eocecm }}'
    become: yes

  - name: Store email txt from remote to DDS
    fetch:
      src: '{{ tracking_dir_server }}/reusability_metrics/lt_reusability_metrics_{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}_{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}.txt'
      dest: '/tmp/reusability_metrics_email'
    register: 'fetch_email'

  - debug:
      var: fetch_email

  - name: Send email with results for reusability metrics
    shell: 'cat {{ fetch_email.dest }} | mailx -S smtp={{ smtp_server }} -r {{ email_from }} -s "Reusability metrics Lithuania  " -v {{ email_to }}'
    delegate_to: localhost
