---
  - name: Check does EOC metadata exist in tracking
    stat:
      path: '{{ tracking_dir_server }}/repo/06-METADATA/2-EOC'
    register: track_eoc_dir_reg
  # if repo folder in working didn't exist then we wouldn't have something to compare to

  - name: Create a empty dir if EOC metadata doesn't exist in tracking
    file:
      path: '{{ tracking_dir_server }}/repo/06-METADATA/2-EOC'
      state: directory
      mode: '0775'
      owner: '{{ user_for_eocecm }}'
      group: '{{ group_for_eocecm }}'
    become: yes
    when: not track_eoc_dir_reg.stat.exists
  # we are creating folder so we can use diff command
  # this only happends if repo in working is not existing when we
  # start this playbook so we can't copy to tracking repo

  - name: Check did EOC metadata changed
    command: 'diff -qr {{ eoc_metadata_path }} {{ tracking_dir_server }}/repo/06-METADATA/2-EOC'
    register: diff_eoc_result
    changed_when: diff_eoc_result.rc != 0
    failed_when: diff_eoc_result.rc == 2

  - debug:
      var: diff_eoc_result

  - name: Register dummy EOC host with variable DUMMY_DIFF_EOC_RESULT
    add_host:
      name: "DUMMY_EOC"
      DUMMY_DIFF_EOC_RESULT: "{{ diff_eoc_result.changed }}"
