---
# tasks file for deploy_sr_war
  - name: Check if sr.war for this environment exist
    stat:
      path: '{{ eoc_deploy_sr_war_file }}'
    register: sr_war_file

  - name: Copy sr.war file for this environment
    copy:
      src: '{{ eoc_deploy_sr_war_file }}'
      dest: '{{ jboss_eoc_dir }}/standalone_{{ eoc_nodeid_service_registry }}/deployments/sr.war'
      remote_src: yes
      mode: '0775'
      owner: '{{ user_for_jboss }}'
      group: '{{ group_for_eocecm }}'
      backup: yes
    register: backup_variable
    become: yes
    when: sr_war_file.stat.isreg is defined

  - name: Check if backup sr.war for this environment exist
    stat:
      path: '{{ backup_variable.backup_file }}'
    register: backup_check
    when: backup_variable.changed and backup_variable.backup_file is defined

  - name: Create a sr.war backup directory if it does not exist
    file:
      path: '{{ config_backup_dir_server }}/sr/sr_{{ date_and_time }}_{{ git_commit_id }}'
      state: directory
      mode: '0775'
      owner: '{{ user_for_jboss }}'
      group: '{{ group_for_eocecm }}'
    become: yes
    when: backup_variable.changed and backup_variable.backup_file is defined and sr_war_file.stat.isreg is defined

  - name: Copy backup of sr.war file
    copy:
      src: '{{ backup_variable.backup_file }}'
      dest: '{{ config_backup_dir_server }}/sr/sr_{{ date_and_time }}_{{ git_commit_id }}/'
      remote_src: yes
      mode: '0775'
      owner: '{{ user_for_jboss }}'
      group: '{{ group_for_eocecm }}'
    become: yes
    ignore_errors: yes
    when: backup_variable.changed and backup_variable.backup_file is defined and sr_war_file.stat.isreg is defined

  - name: Delete backup of sr.war file from deployments folder
    file:
      path: '{{ backup_variable.backup_file }}'
      state: absent
    become: yes
    when: backup_variable.changed and backup_variable.backup_file is defined and sr_war_file.stat.isreg is defined

  - name: Sleep for 20 seconds and continue with play
    wait_for:
      timeout: 20
    when: backup_variable.changed and sr_war_file.stat.isreg is defined

  - name: Delete sr.war.deployed/undeployed files from deployments folder
    file:
      path: '{{ item }}'
      state: absent
    become: yes
    with_items:
      # - '{{ jboss_eoc_dir }}/standalone_sr/deployments/sr.war.deployed'
      - '{{ jboss_eoc_dir }}/standalone_{{ eoc_nodeid_service_registry }}/deployments/sr.war.undeployed'
      - '{{ jboss_eoc_dir }}/standalone_{{ eoc_nodeid_service_registry }}/deployments/sr.war.failed'
    when: backup_variable.changed and sr_war_file.stat.isreg is defined

  - name: Sleep for 30 seconds and continue with play
    wait_for:
      timeout: 30
    when: backup_variable.changed and sr_war_file.stat.isreg is defined

  - name: Check does sr.war.deployed file exist in deployments folder
    stat:
      path: '{{ jboss_eoc_dir }}/standalone_{{ eoc_nodeid_service_registry }}/deployments/sr.war.deployed'
    register: sr_war_deployed_file

  # - name: Fail if sr.war.deployed is not present
  #   fail:
  #     msg: File sr.war is not deployed.
  #   when: sr_war_deployed_file.stat.exists == false
