name: VM PREPROD PROD Shared Workflow | EOC-TCS 
on:
  workflow_dispatch:
jobs:
  deployment:
    runs-on: ubuntu-latest   
    steps:

    
      - name: Check out Ansible repository code
        uses: actions/checkout@v3
        with:
          ref: ansible
          path: ansible-files
          
      - name: Check current folder
        run: |
          pwd
          ls -alh

      - name: Check ansible folder
        run: |
          cd ansible-files
          pwd
          ls -alh

