name: VM PREPROD PROD Shared Workflow | EOC-TCS 
on:
  workflow_dispatch:
jobs:
  deployment:
    runs-on: ubuntu-latest   
    steps:
      - name: Prepare the folder
        run: | 
          cd $GITHUB_WORKSPACE
          mkdir ansible-files
          cd ansible-files
          pwd
          ls -alh
    
      - name: Check out Ansible repository code
        uses: actions/checkout@v3
        with:
          ref: ansible

      - name: Check ansible folder
        run: |
          pwd
          ls -alh

      - name: Check GITHUB_WORKSPACE
        run: |
          cd $GITHUB_WORKSPACE
          pwd
          ls -alh
